version: '3.7'

services:
  pancake:
    build: .
    command: bash -c "cd app/ && python3 test.py && sleep 600"
    environment:
      - DEBUG=1
      - FACTORY_ADDRESS=0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73
    volumes:
      - ./:/app
    networks:
      - main_network
  
  biswap:
    build: .
    command: bash -c "cd app/ && python3 test.py && sleep 600"
    environment:
      - DEBUG=2
      - FACTORY_ADDRESS=0x858E3312ed3A876947EA49d572A7C42DE08af7EE
    volumes:
      - ./:/app
    networks:
      - main_network


networks:
  main_network: