version: '3.7'

services:
  pancake:
    build: .
    command: bash -c "cd app/ && python3 init_db.py && python3 get_dex_pairs.py"
    restart: always
    environment:
      - DEBUG=1
      - FACTORY_ADDRESS=0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73
      - ROUTER_ADDRESS=0x10ED43C718714eb63d5aA57B78B54704E256024E
    volumes:
      - ./:/app
    networks:
      - main_network
  
  biswap:
    build: .
    command: bash -c "cd app/ && python3 init_db.py && python3 get_dex_pairs.py"
    restart: always
    environment:
      - DEBUG=2
      - FACTORY_ADDRESS=0x858E3312ed3A876947EA49d572A7C42DE08af7EE
      - ROUTER_ADDRESS=0x3a6d8cA21D1CF76F653A67577FA0D27453350dD8
    volumes:
      - ./:/app
    networks:
      - main_network
  
  apeswap:
    build: .
    command: bash -c "cd app/ && python3 init_db.py && python3 get_dex_pairs.py"
    restart: always
    environment:
      - DEBUG=3
      - FACTORY_ADDRESS=0x0841BD0B734E4F5853f0dD8d7Ea041c241fb0Da6
      - ROUTER_ADDRESS=0xcF0feBd3f17CEf5b47b0cD257aCf6025c5BFf3b7
    volumes:
      - ./:/app
    networks:
      - main_network


networks:
  main_network: