version: '3.7'

services:
  pancake:
    build: .
    container_name: pancake
    command: bash -c "cd app/ && python3 init_db.py && python3 get_dex_pairs.py"
    restart: always
    environment:
      - DEBUG=1
      - FACTORY_ADDRESS=0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73
      - ROUTER_ADDRESS=0x10ED43C718714eb63d5aA57B78B54704E256024E
    volumes:
      - ./:/app
    networks:
      - main_network
    depends_on:
      - postgres
  
  biswap:
    build: .
    container_name: biswap
    command: bash -c "cd app/ && python3 init_db.py && python3 get_dex_pairs.py"
    restart: always
    environment:
      - DEBUG=2
      - FACTORY_ADDRESS=0x858E3312ed3A876947EA49d572A7C42DE08af7EE
      - ROUTER_ADDRESS=0x3a6d8cA21D1CF76F653A67577FA0D27453350dD8
    volumes:
      - ./:/app
    networks:
      - main_network
    depends_on:
      - postgres
  
  apeswap:
    build: .
    container_name: apeswap
    command: bash -c "cd app/ && python3 init_db.py && python3 get_dex_pairs.py"
    restart: always
    environment:
      - DEBUG=3
      - FACTORY_ADDRESS=0x0841BD0B734E4F5853f0dD8d7Ea041c241fb0Da6
      - ROUTER_ADDRESS=0xcF0feBd3f17CEf5b47b0cD257aCf6025c5BFf3b7
    volumes:
      - ./:/app
    networks:
      - main_network
    depends_on:
      - postgres
  
  postgres:
    image: postgres:14.8-alpine3.18
    container_name: db
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres_password"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - main_network


volumes:
  postgres_data:

networks:
  main_network: